<?php
  $lang['number']		= 'Numeris';
  $lang['date'] 		= 'Pirkimo data';
  $lang['time']			= 'Pirkimo laikas';
  $lang['due'] 			= 'Apmokėti iki';
  $lang['to'] 			= 'Gavėjas';
  $lang['from'] 		= 'Pardavėjas';
  $lang['product'] 		= 'Paslauga';
  $lang['qty'] 			= 'Kiekis';
  $lang['price'] 		= 'Kaina';
  $lang['discount'] 	= 'Nuolaida';
  $lang['vat'] 			= 'PVM';
  $lang['total'] 		= 'Iš viso';
  $lang['page'] 		= 'Puslapis';
  $lang['page_of'] 		= 'iš';
?>